resources folder is created, runThisCase files have been updated

diff --git a/benchmarks/helicalMixer/helicalMixer_250K/runThisCase b/benchmarks/helicalMixer/helicalMixer_250K/runThisCase
--- a/benchmarks/helicalMixer/helicalMixer_250K/runThisCase
+++ b/benchmarks/helicalMixer/helicalMixer_250K/runThisCase
@@ -1,5 +1,12 @@
 #!/bin/sh
+set -e  # Exit immediately if a command exits with a non-zero status
 cd ${0%/*} || exit 1    # Run from this directory
+
+echo "\n<--------------------------------------------------------------------->"
+echo "0) Copying stl files"
+echo "\n<--------------------------------------------------------------------->"
+mkdir -p stl
+cp -rfv $pFlow_PROJECT_DIR/resources/stls/helicalMixer/* ./stl/
 echo "\n<--------------------------------------------------------------------->"
 echo "1) Creating particles"
 echo "<--------------------------------------------------------------------->\n"
diff --git a/tutorials/sphereGranFlow/conveyorBelt/runThisCase b/tutorials/sphereGranFlow/conveyorBelt/runThisCase
--- a/tutorials/sphereGranFlow/conveyorBelt/runThisCase
+++ b/tutorials/sphereGranFlow/conveyorBelt/runThisCase
@@ -1,4 +1,5 @@
 #!/bin/sh
+set -e  # Exit immediately if a command exits with a non-zero status
 cd ${0%/*} || exit 1    # Run from this directory
 echo "\n<--------------------------------------------------------------------->"
 echo "1) Creating particles"
